server:
  port: 8083
spring:
  application:
    name: "reportes"
  devtools:
    add-properties: false
    restart:
      enabled: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
    active: local
aws:
  region: "us-east-2"
  dynamodb:
    endpoint: "https://dynamodb.us-east-2.amazonaws.com"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapter:
  sqs:
    region: "us-east-2"
    solicitudesAprobadasQueue: "https://sqs.us-east-2.amazonaws.com/560580021338/solicitudes-aprobadas-queue"
